// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcxtaxzqeqwugovvnoly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjeHRheHpxZXF3dWdvdnZub2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDk0MDgsImV4cCI6MjA4NTAyNTQwOH0.wQCDIaJtCG0DiNMjKeFrHshDuHc8lyOpFnZrz9rWp1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});